package app.preciojusto.products.exceptions;

import lombok.Getter;

public enum ApplicationExceptionCode {
    UNKNOWN_ERROR(0),
    PRODUCT_NOT_FOUND_ERROR(1),
    BRAND_NOT_FOUND_ERROR(2),
    CATEGORY_NOT_FOUND_ERROR(3),
    OFFER_NOT_FOUND_ERROR(4),
    PACK_NOT_FOUND_ERROR(5),
    RECIPE_NOT_FOUND_ERROR(6),
    SUPERMARKET_NOT_FOUND_ERROR(7),
    PRODUCT_ALREADY_EXISTS_ERROR(8),
    BRAND_ALREADY_EXISTS_ERROR(9),
    CATEGORY_ALREADY_EXISTS_ERROR(10),
    OFFER_ALREADY_EXISTS_ERROR(11),
    PACK_ALREADY_EXISTS_ERROR(12),
    RECIPE_ALREADY_EXISTS_ERROR(13),
    SUPERMARKET_ALREADY_EXISTS_ERROR(14),
    PRODUCT_NO_CONTENT_ERROR(15),
    BRAND_NO_CONTENT_ERROR(16),
    CATEGORY_NO_CONTENT_ERROR(17),
    OFFER_NO_CONTENT_ERROR(18),
    PACK_NO_CONTENT_ERROR(19),
    RECIPE_NO_CONTENT_ERROR(20),
    SUPERMARKET_NO_CONTENT_ERROR(21),
    BADREQUEST_ERROR(22),
    UNAUTHORIZED_ERROR(23),
    BADGATEWAY_ERROR(24);


    @Getter
    private int code;
    ApplicationExceptionCode(int code) {
        this.code = code;
    }
}
