package app.preciojusto.products.exceptions;

import lombok.Getter;

public enum ApplicationExceptionCode {
    UNKNOWN_ERROR(-1),

    NOT_FOUND_ERROR(0),
    PRODUCT_NOT_FOUND_ERROR(1),
    BRAND_NOT_FOUND_ERROR(2),
    CATEGORY_NOT_FOUND_ERROR(3),
    OFFER_NOT_FOUND_ERROR(4),
    PACK_NOT_FOUND_ERROR(5),
    RECIPE_NOT_FOUND_ERROR(6),
    SUPERMARKET_NOT_FOUND_ERROR(7),
    CONTAINER_NOT_FOUND_ERROR(8),
    FOODPRODUCT_NOT_FOUND_ERROR(9),
    SUPERMARKETPRODUCT_NOT_FOUND_ERROR(10),

    ALREADY_EXISTS_ERROR(100),
    PRODUCT_ALREADY_EXISTS_ERROR(101),
    BRAND_ALREADY_EXISTS_ERROR(102),
    CATEGORY_ALREADY_EXISTS_ERROR(103),
    OFFER_ALREADY_EXISTS_ERROR(104),
    PACK_ALREADY_EXISTS_ERROR(105),
    RECIPE_ALREADY_EXISTS_ERROR(106),
    SUPERMARKET_ALREADY_EXISTS_ERROR(107),
    CONTAINER_ALREADY_EXISTS_ERROR(108),
    FOODPRODUCT_ALREADY_EXISTS_ERROR(109),
    SUPERMARKETPRODUCT_ALREADY_EXISTS_ERROR(110),

    NO_CONTENT_ERROR(200),
    PRODUCT_NO_CONTENT_ERROR(201),
    BRAND_NO_CONTENT_ERROR(202),
    CATEGORY_NO_CONTENT_ERROR(203),
    OFFER_NO_CONTENT_ERROR(204),
    PACK_NO_CONTENT_ERROR(205),
    RECIPE_NO_CONTENT_ERROR(206),
    SUPERMARKET_NO_CONTENT_ERROR(207),
    CONTAINER_NO_CONTENT_ERROR(208),
    FOODPRODUCT_NO_CONTENT_ERROR(209),
    SUPERMARKETPRODUCT_NO_CONTENT_ERROR(210),

    BADREQUEST_ERROR(301),
    UNAUTHORIZED_ERROR(302),
    BADGATEWAY_ERROR(303);


    @Getter
    private final int code;

    ApplicationExceptionCode(int code) {
        this.code = code;
    }
}
